---
title: "Assignment 15"
authors:
- Bryana Benson
- Conner Bryan
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---
    
```{r warning=FALSE, message=FALSE}
library(flexdashboard)
library(Quandl)
library(readr)
library(dygraphs)
library(stats)
library(ggplot2)
url<-"http://www.richardtwatson.com/data/manheim.csv"
manheim<-read_csv(url)
```
    
    
Row
-------------------------------------
    
### Number of Models sold at each Sale Type
    
```{r}
tab<-xtabs(~model + sale, data=manheim)
ftable(tab)
```
 
### Price Range for each Model
    
```{r}
ggplot(manheim,aes(model,price)) +
  geom_boxplot(outlier.colour='red') +
  xlab("Model") + ylab("Price $")
``` 

Row
-------------------------------------
    
### Scatterplot: Miles & Price by Model
    
```{r}
ggplot(manheim,aes(miles,price,color=model)) +
  geom_point() +
  xlab("Miles") + ylab("Price $")
```
    
### Scatterplot: Miles & Price by Sale Type

```{r}
ggplot(manheim,aes(miles,price,color=sale)) +
  geom_point() +
  xlab("Miles") + ylab("Price $")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```